### ISSUE TITLE
My IDE file background is white 

### ISSUE THREAD

**Issue by DarkStarStrix** [SIDSSIDS/jetbrains-cyberpunk-neon-theme#26]
![Screenshot 2024-03-20 121605](https://github.com/SIDSSIDS/jetbrains-cyberpunk-neon-theme/assets/108637439/7c488400-b65b-4f66-be9e-510823da2165)
I've tried uninstalling and reinstalling it again it's not working can you change the theme back the orginal

**Comment by DarkStarStrix** [comment]
oh never mind got it

**Comment by patrickmcanuff** [comment]
How did you fix it? This just happened to me as well with the latest update. Both my main window and terminal windows are white.

**Comment by DarkStarStrix** [comment]
Yeah so I was retracing and you go settings editor then color scheme then change it to the cyberpunk neon theme

**Comment by patrickmcanuff** [comment]
Amazing, that worked. Thank you!
