### ISSUE TITLE
Add Support For Intellij 2024.2

### ISSUE THREAD

**Issue by LatestPhysx** [SIDSSIDS/jetbrains-cyberpunk-neon-theme#47]
Hello, this theme is not supported on intellij idea 2024.2, it would be awesome to add support, thanks in advance.

**Comment by SIDSSIDS** [comment]
Hi @AFBadBoy 
Thanks for reporting it.

I've deleted the `until-build` attribute so the plugin will be supported by all new Intellij Idea versions. I don't know why I haven't done it earlier...

Please, update the plugin to `1.0.5` version when it becomes available (usually it takes 2 business days from JetBrains team to approve the new plugin version)

**Comment by LatestPhysx** [comment]
thank you for the quick timing  :)
